language: python
sudo: required
dist: xenial

python:
  - "3.6"
addons:
  ssh_known_hosts: $DEPLOY_SERVER:$DEPLOY_PORT
os:
  - linux

before_deploy:
  - openssl aes-256-cbc -K $encrypted_320490501875_key -iv $encrypted_320490501875_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy_rsa
  - chmod a+x ./deploy.sh

jobs:
  include:
    - stage: "Tests and Linting"
      name: "Unit Tests"
      install:
        - pip install pipenv
        - pipenv install --dev
      script: coverage run -m unittest discover
      after_success: coveralls

    - name: "Linting"
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - mypy .
        - flake8

    - stage: "Deploy"
      name: "Deploy to Live"
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          ssh -p $DEPLOY_PORT $SSH_LOGIN_USERNAME@$DEPLOY_SERVER "bash $DEPLOY_SCRIPT -c $TRAVIS_COMMIT -d $LIVE_DEPLOY_DIR -n $DCK_CNT_NAME -i DCK_IMAGE_NAME"
        on:
          branch: master